version: '3'

services:
  metricbeat:
    image: ${CI_REGISTRY_IMAGE}/${COMPOSE_PROJECT_NAME}_metricbeat_${AGENT_HOST}
    build:
      context: ../../agent-templates/metricbeat
    container_name: ${COMPOSE_PROJECT_NAME}_metricbeat
    restart: always
    network_mode: host
    environment:
      - ELASTIC_ROOT_USER=${ELASTIC_ROOT_USER}
      - ELASTIC_ROOT_PASSWORD=${ELASTIC_ROOT_PASSWORD}
      - SERVER_HOST=${SERVER_HOST}
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
